In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/netflix-shows/netflix_titles.csv


# Numpy

*  Basic difference between Python list and NumPy is that Numy arrays are more efficient for numerical operations
  

In [11]:
python_list = [1,2,3,4,5,6]

np_array = np.array(python_list)

print(np_array)

print("Python list * 3:", python_list * 3)
print("Numpy array * 3:", np_array * 3)

print(np_array ** 2)

print("Array shape: ", np_array.shape)
print("Mean of array:", np_array.mean())

arr = np_array.reshape(2, 3)
print("Reshaped array: ", arr)

print("Transpose array: ", arr.T)

print("Access sub array: ", arr[1:2, 0:2])

[1 2 3 4 5 6]
Python list * 3: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
Numpy array * 3 :  [ 3  6  9 12 15 18]
[ 1  4  9 16 25 36]
Array shape:  (6,)
Mean of array: 3.5
Reshaped array:  [[1 2 3]
 [4 5 6]]
Transpose array:  [[1 4]
 [2 5]
 [3 6]]
Access sub array:  [[4 5]]


In [17]:
# Filtering using masks

mask = arr > 2

print("Filtered array: ", arr[mask])

mask2 = arr % 2 == 0

print("filtered array: ", arr[mask2])


# Adding arrays using Broadcasting

arr1 = np.array([1,2,3])

# Create a 2D array
arr2 = np.array([[4], [5], [3]])

# Add arrays using broadcasting

result = arr1 + arr2 

print("Array 1: \n", arr1)
print("Array 2: \n", arr2)
print("Result of broadcasting:\n", result)

Filtered array:  [3 4 5 6]
filtered array:  [2 4 6]
Array 1: 
 [1 2 3]
Array 2: 
 [[4]
 [5]
 [3]]
Result of broadcasting:
 [[5 6 7]
 [6 7 8]
 [4 5 6]]


# Loading the Netflix Titles dataframe

In [22]:
# Load the dataset: Use Pandas to read the CSV file

df = pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

# peek at data
df.head(10)

#df.tail()

#print(df)


show_id     type                             title  \
0      s1    Movie              Dick Johnson Is Dead   
1      s2  TV Show                     Blood & Water   
2      s3  TV Show                         Ganglands   
3      s4  TV Show             Jailbirds New Orleans   
4      s5  TV Show                      Kota Factory   
5      s6  TV Show                     Midnight Mass   
6      s7    Movie  My Little Pony: A New Generation   
7      s8    Movie                           Sankofa   
8      s9  TV Show     The Great British Baking Show   
9     s10    Movie                      The Starling   

                        director  \
0                Kirsten Johnson   
1                            NaN   
2                Julien Leclercq   
3                            NaN   
4                            NaN   
5                  Mike Flanagan   
6  Robert Cullen, José Luis Ucha   
7                   Haile Gerima   
8                Andy Devonshire   
9                 Theodore Melfi   

                                                cast  \
0                                                NaN   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
3                                                NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   
5  Kate Siegel, Zach Gilford, Hamish Linklater, H...   
6  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
7  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...   
8  Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...   
9  Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   

                                             country          date_added  \
0                                      United States  September 25, 2021   
1                                       South Africa  September 24, 2021   
2                                                NaN  September 24, 2021   
3                                                NaN  September 24, 2021   
4                                              India  September 24, 2021   
5                                                NaN  September 24, 2021   
6                                                NaN  September 24, 2021   
7  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021   
8                                     United Kingdom  September 24, 2021   
9                                      United States  September 24, 2021   

   release_year rating   duration  \
0          2020  PG-13     90 min   
1          2021  TV-MA  2 Seasons   
2          2021  TV-MA   1 Season   
3          2021  TV-MA   1 Season   
4          2021  TV-MA  2 Seasons   
5          2021  TV-MA   1 Season   
6          2021     PG     91 min   
7          1993  TV-MA    125 min   
8          2021  TV-14  9 Seasons   
9          2021  PG-13    104 min   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   
5                 TV Dramas, TV Horror, TV Mysteries   
6                           Children & Family Movies   
7   Dramas, Independent Movies, International Movies   
8                       British TV Shows, Reality TV   
9                                   Comedies, Dramas   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...  
5  The arrival of a charismatic young priest brin...  
6  Equestria's divided. But a bright-eyed hero be...  
7  On a photo shoot in Ghana, an American model s...  
8  A talented 

In [32]:
# how to access a single column
#print(df[['title', 'country']].head(10))

# Find missing values: Check how many values are missing in each column
df.isnull().sum()

# handle missing data
# Fill missing categorical data with 'Unknown'
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

# Filtering and Transforming Data

In [35]:
# Filter for TV shows produced in India

indian_shows = df[(df['country'].str.contains('India') & (df['type'] == 'TV Show')) ]

indian_shows.shape
indian_shows.head()

show_id     type                           title director  \
4       s5  TV Show                    Kota Factory  Unknown   
39     s40  TV Show                    Chhota Bheem  Unknown   
50     s51  TV Show                   Dharmakshetra  Unknown   
66     s67  TV Show   Raja Rasoi Aur Anya Kahaniyan  Unknown   
69     s70  TV Show  Stories by Rabindranath Tagore  Unknown   

                                                 cast country  \
4   Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   India   
39  Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...   India   
50  Kashmira Irani, Chandan Anand, Dinesh Mehta, A...   India   
66                                 David Attenborough   India   
69                                 David Attenborough   India   

            date_added  release_year rating   duration  \
4   September 24, 2021          2021  TV-MA  2 Seasons   
39  September 16, 2021          2021  TV-Y7  3 Seasons   
50  September 15, 2021          2014  TV-PG   1 Season   
66  September 15, 2021          2014   TV-G   1 Season   
69  September 15, 2021          2015  TV-PG   1 Season   

                                            listed_in  \
4   International TV Shows, Romantic TV Shows, TV ...   
39                                           Kids' TV   
50  International TV Shows, TV Dramas, TV Sci-Fi &...   
66                 Docuseries, International TV Shows   
69                  International TV Shows, TV Dramas   

                                          description  
4   In a city of coaching centers known to train I...  
39  A brave, energetic little boy with superhuman ...  
50  After the ancient Great War, the god Chitragup...  
66  Explore the history and flavors of regional In...  
69  The writings of Nobel Prize winner Rabindranat...

In [37]:
#Filter for movies released after 2015

recent_movies = df[(df['type']  == 'Movie') & (df['release_year'] > 2015)]

recent_movies.shape
recent_movies.head()

show_id   type                             title director  \
0       s1  Movie              Dick Johnson Is Dead  Unknown   
6       s7  Movie  My Little Pony: A New Generation  Unknown   
9      s10  Movie                      The Starling  Unknown   
12     s13  Movie                      Je Suis Karl  Unknown   
13     s14  Movie  Confessions of an Invisible Girl  Unknown   

                                                 cast  \
0                                  David Attenborough   
6   Vanessa Hudgens, Kimiko Glenn, James Marsden, ...   
9   Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...   
12  Luna Wedler, Jannis Niewöhner, Milan Peschel, ...   
13  Klara Castanho, Lucca Picon, Júlia Gomes, Marc...   

                    country          date_added  release_year rating duration  \
0             United States  September 25, 2021          2020  PG-13   90 min   
6             United States  September 24, 2021          2021     PG   91 min   
9             United States  September 24, 2021          2021  PG-13  104 min   
12  Germany, Czech Republic  September 23, 2021          2021  TV-MA  127 min   
13            United States  September 22, 2021          2021  TV-PG   91 min   

                             listed_in  \
0                        Documentaries   
6             Children & Family Movies   
9                     Comedies, Dramas   
12        Dramas, International Movies   
13  Children & Family Movies, Comedies   

                                          description  
0   As her father nears the end of his life, filmm...  
6   Equestria's divided. But a bright-eyed hero be...  
9   A woman adjusting to life after a loss contend...  
12  After most of her family is murdered in a terr...  
13  When the clever but socially-awkward Tetê join...

In [39]:
# Count the number of movies and TV shows using value_counts()
movies_tv_count = df['type'].value_counts()
print("Movies vs TV shows: ", movies_tv_count)

country_count = df['country'].value_counts()
print(country_count)

Movies vs TV shows:  type
Movie      6131
TV Show    2676
Name: count, dtype: int64
country
United States                             3649
India                                      972
United Kingdom                             419
Japan                                      245
South Korea                                199
                                          ... 
Romania, Bulgaria, Hungary                   1
Uruguay, Guatemala                           1
France, Senegal, Belgium                     1
Mexico, United States, Spain, Colombia       1
United Arab Emirates, Jordan                 1
Name: count, Length: 748, dtype: int64


In [41]:
# NumPy operations on DF

years = np.array(df['release_year'])

print("Mean release year: ", np.mean(years))
print("Standard Deviation: ", np.std(years))

Mean release year:  2014.1801975701146
Standard Deviation:  8.818811417623195
